name: automata_theory
description: Implementations of DFA, NFA and eNFA in Dart language
# author: Pedro Lemos <lemozxpedro@gmail.com>
homepage: https://github.com/pedrolemoz/AutomataTheory
version: 2.1.0

environment:
  sdk: '^3.5.0'

dev_dependencies:
  test: ^1.25.8